#!/bin/sh

if [ -f "venv/bin/python3" ]; then PYTHON_COMMAND="venv/bin/python3"; else PYTHON_COMMAND="venv/bin/python"; fi

export EDBN_DBMS_CHOICE="1"

initdb -D "./db"
sed -i "/unix_socket_directories =/c\unix_socket_directories = ''" db/postgresql.conf
createdb -h localhost edbn
$PYTHON_COMMAND py/initdb.py
