#!/bin/sh

if [ -f "venv/bin/pip3" ]; then PIP_COMMAND="venv/bin/pip3"; else PIP_COMMAND="venv/bin/pip"; fi
if [ -x "$(command -v python3)" ]; then PYTHON_COMMAND="python3"; else PYTHON_COMMAND="python"; fi

mkdir db
mkdir raw
mkdir tools

$PYTHON_COMMAND -m venv venv
$PIP_COMMAND install -r requirements.txt

$PYTHON_COMMAND py/initdb.py
